[project]
name = "pokemon-card-detector"
version = "1.0.0"
description = "AI-powered Pokemon card authenticity detector optimized for Railway deployment"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=21.2.0",
    "pillow>=10.0.1",
    "opencv-python>=4.8.1.78",
    "numpy>=1.24.3",
    "pytesseract>=0.3.10",
    "psycopg2-binary>=2.9.7",
    "werkzeug>=3.0.0",
    "sqlalchemy>=2.0.23",
    "requests>=2.31.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]