[build]
builder = "nixpacks"

[deploy]
startCommand = "DEPLOYMENT_MODE=true gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 1 --timeout 300 main:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
DEPLOYMENT_MODE = "true"
FLASK_ENV = "production"